# Generated by Django 4.1.1 on 2022-11-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(default='', upload_to='img')),
                ('teacher_name', models.CharField(max_length=30)),
                ('total_hours', models.IntegerField()),
                ('total_students', models.IntegerField()),
            ],
        ),
    ]
