# Generated by Django 4.1.1 on 2022-11-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_caurosel'),
    ]

    operations = [
        migrations.AddField(
            model_name='caurosel',
            name='picture',
            field=models.ImageField(default='', upload_to='img'),
        ),
    ]
