# Generated by Django 4.1.4 on 2022-12-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_caurosel2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caurosel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('picture', models.ImageField(default='', upload_to='img')),
            ],
        ),
    ]
