# Generated by Django 4.1.1 on 2022-11-07 20:42

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30000000)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
