# Generated by Django 3.2.16 on 2023-01-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangla_to_france', '0002_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='', upload_to='img'),
        ),
    ]
